apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghcr-app
  namespace: ghcr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghcr-app
  template:
    metadata:
      labels:
        app: ghcr-app
    spec:
      containers:
        - name: ghcr-app
          image: ghcr.io/ppbrown/ghcr-test:12 # {"$imagepolicy": "flux-system:ghcr-app"}
          ports:
            - containerPort: 8080
