apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: ghcr-test
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: fluxcd-ghcr-app-write
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        Auto-update ghcr-test image tag

        {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: main
  update:
    path: ./
    strategy: Setters
